services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: gads
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: gads
    ports:
      - 5432:5432
    container_name: db
    expose:
      - 5432
  app:
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "chmod +x /app/bin/docker.sh && sh /app/bin/docker.sh admin@localhost qwedsa localhost"
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - .:/app
    depends_on:
      - db
  frontend:
    image: node:16-alpine
    volumes:
      - .:/frontend
    working_dir: /frontend
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "chmod +x /frontend/bin/frontend.sh && sh /frontend/bin/frontend.sh"