check_yarn:
	@echo "Checking for yarn"
	@yarn --version || (echo "yarn is not installed. Please install it from https://yarnpkg.com/getting-started/install" && exit 1)

yarn: check_yarn
	@echo "Installing node modules"
	@yarn --frozen-lockfile
	@npx update-browserslist-db@latest

yarn_build: yarn
	@echo "Building Bundles"
	@NODE_ENV=production yarn webpack
	@git checkout ./public/js/fengari-web.js

build_web: yarn_build

deb_mkdirs:
	@echo "Creating Directories"
	@mkdir -p GADS-$(VERSION)/srv/GADS
	@mkdir -p GADS-$(VERSION)/DEBIAN

deb_copy: deb_mkdirs
	@echo "Copying files"
	@cp -r bin environments lib public share views config.yml-example GADS-$(VERSION)/srv/GADS

deb_control: deb_copy
	@rm -f GADS-$(VERSION)/DEBIAN/control
	@echo "Creating package manifest"
	@echo "Package: GADS" > GADS-$(VERSION)/DEBIAN/control
	@echo "Version: $(VERSION)" >> GADS-$(VERSION)/DEBIAN/control
	@echo "Section: database" >> GADS-$(VERSION)/DEBIAN/control
	@echo "Priority: optional" >> GADS-$(VERSION)/DEBIAN/control
	@echo "Architecture: amd64" >> GADS-$(VERSION)/DEBIAN/control
%prereq%
	@echo 'Recommends: postgresql (>= 0)' >> GADS-$(VERSION)/DEBIAN/control
	@echo "Maintainer: CtrlO Ltd <info@ctrlo.com>" >> GADS-$(VERSION)/DEBIAN/control
	@echo "Description: Globally Accessible Data Store (GADS) is a web application for storing and sharing data across an organisation." >> GADS-$(VERSION)/DEBIAN/control
	@echo " It provides a simple interface for creating and managing data, as well as powerful features for sharing and collaborating on data with others." >> GADS-$(VERSION)/DEBIAN/control
	@echo " GADS is built using the Dancer2 web framework and is designed to be easy to use and extendable." >> GADS-$(VERSION)/DEBIAN/control
	@echo "Vcs-Git: https://github.com/ctrlo/GADS.git" >> GADS-$(VERSION)/DEBIAN/control

deb_package: deb_control
	@echo "Creating package for GADS-$(VERSION)"
	@cd GADS-$(VERSION)
	@dpkg-deb --build ./GADS-$(VERSION) ./GADS_$(VERSION).deb

deb_clean: deb_package
	@echo "Cleaning up..."
	@rm -rf GADS-$(VERSION)

deb_build: build_web deb_clean
