package GADS::PDFGenerator;

use strict;
use warnings;

use Moo;

use GADS::Config;

use CtrlO::PDF;

has site => (
    is => 'ro',
    required => 1,
);

has layouts => (
    is => 'ro',
    required => 1,
);

has record => (
    is => 'ro',
    required => 1
);

has user => (
    is => 'ro',
    required => 1,
);

has security_marking => (
    is => 'ro',
);

has _default_marking => (
    is => 'lazy',
);

sub _build__default_marking {
    return shift->site->read_security_marking;
}

has _logo => (
    is => 'lazy',
);

sub _build__logo {
    return shift->site->create_temp_logo;
}

sub build {
    my ($self, %options) = @_;
    
    my $marking = $self->security_marking || $self->_default_marking;
    my $logo    = $self->_logo;

    my $pdf;
    my $topmargin = 0;

    if ($logo)
    {
        $pdf = CtrlO::PDF->new(
            header => $marking,
            footer => $marking,
            logo   => $logo,
        );

        # Adjust the top margin to allow for the logo - 30px allows the table (below the logo) to not encroach on the logo when rendered
        # This is used rather than overcomplicating and using image size to centre the header, and then having to "drop" the table down to avoid the logo
        $topmargin = -30;
    }
    else
    {
        $pdf = CtrlO::PDF->new(
            header => $marking,
            footer => $marking,
        );
    }

    $pdf->add_page;

    $pdf->heading($options{title}, topmargin => $topmargin);
    $pdf->text($options{subtitle}, size => 14) if $options{subtitle};

    my $hdr_props = {
        repeat    => 0,
        justify   => 'center',
        font_size => 12,
        bg_color  => '#007c88',
        fg_color  => '#ffffff',
    };

    my $result = $self->layouts;

    my @cols = $self->record->presentation_map_columns(columns => $result);
    my @topics = $self->record->get_topics(\@cols);

    my $i = 0;
    foreach my $topic (@topics)
    {
        my $topic_name = $topic->{topic} ? $topic->{topic}->name : 'Other';
        my $fields     = [ [$topic_name] ];

        my $width = 0;
        foreach my $col (@{ $topic->{columns} })
        {
            if ($col->{data}->{selected_values})
            {
                my $first = 1;
                foreach my $c (@{ $col->{data}->{selected_values} })
                {
                    my $values = $c->{values};
                    $width =
                        $width < (scalar(@$values) + 1)
                        ? scalar(@$values) + 1
                        : $width;
                    push @$fields, [ $first ? $col->{name} : '', @$values ];
                    $first = 0;
                }
            }
            else
            {
                if ($col->{data}->{value})
                {
                    push @$fields,
                        [ $col->{name}, $col->{data}->{value} || "" ];
                }
                else
                {
                    push @$fields, [ $col->{name}, $col->{data}->{grade} ];
                }
                $width = 2 if $width < 2;
            }
        }

        my $cell_props = [];
        foreach my $d (@$fields)
        {
            my $has = @$d;

            # $max_fields does not include field name
            my $gap = $width - $has + 1;
            push @$d, undef for (1 .. $gap);
            push @$cell_props,
                [ (undef) x ($has - 1), { colspan => $gap + 1 }, ];
        }

        $pdf->table(
            data         => $fields,
            header_props => $hdr_props,
            border_c     => '#007C88',
            h_border_w   => 1,
            cell_props   => $cell_props,
            size         => '4cm *',
        );
    }

    my $now    = DateTime->now;
    my $format = GADS::Config->instance->dateformat;
    $pdf->text(
        'Last edited by '
            . $self->record->edited_user->as_string . ' on '
            . $self->record->edited_time->as_string,
        size => 10
    );
    $pdf->text(
        'Report generated by '
            . $self->user->value . ' on '
            . $now->format_cldr($format) . ' at '
            . $now->hms,
        size => 10
    );

    return $pdf;
}

1;
