name: 'GADS Tests'
on:
  push:
    branches:
      - master
      - dev
      - hotfix
    paths-ignore:
      - '*.md'
      - VERSION
  pull_request:
    branches:
      - master
      - dev
      - hotfix
    paths-ignore:
      - '*.md'
      - VERSION

jobs:
  unit_tests:
    name: 'Unit Tests'
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 30
    container: debian:trixie-slim

    steps:
      - name: 'Check out the GADS repository'
        uses: 'actions/checkout@v4'
      - name: 'Install dependencies'
        run: |
          chmod +x ./.github/workflows/install.sh
          ./.github/workflows/install.sh
      - name: 'Run the unit tests'
        run: prove -lrs -j4 t

  cypress_tests:
    name: 'Cypress Tests for ${{ matrix.browser.name }}'
    runs-on: '${{ matrix.browser.os }}'
    timeout-minutes: 30
    container: debian:trixie-slim

    strategy:
      fail-fast: false
      matrix:
        browser:
          - name: 'chrome'
            os: 'ubuntu-22.04'
            node_version: '24.21.0'

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespassword
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    env:
      GADS_USERNAME: 'test@example.com'
      GADS_PASSWORD: 'xyz123'

    steps:
      - name: 'Check out the GADS code'
        uses: 'actions/checkout@v4'
      - name: 'Install Non-CPAN dependencies'
        run: |
          chmod +x ./.github/workflows/install.sh
          ./.github/workflows/install.sh
      - name: 'Set up credentials for psql'
        # See https://wiki.postgresql.org/wiki/Pgpass
        run: |
          echo '*:*:*:postgres:postgrespassword' > ~/.pgpass
          chmod 600 ~/.pgpass
      - name: 'Install YARN dependencies'
        run: |
          apt-get install -yq libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.8/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install ${{ matrix.browser.node_version }}
          nvm use ${{ matrix.browser.node_version }}
          npm i -g yarn && npm i -g --allow-scripts=yarn
          yarn --frozen-lockfile
          yarn build --no-watch
      - name: 'create uploads directory'
        run: |
          mkdir -p /tmp/uploads
          chmod 777 /tmp/uploads
      - name: 'Start the application'
        env:
          DANCER_CONFDIR: 'webdriver'
          PGDATABASE: 'postgres'
          PGHOST: 'localhost'
          PGUSER: 'postgres'
          TEST: '1'
        run: |
          ./bin/setup_database
          perl bin/app.pl &
      - name: 'Run the Cypress tests'
        run: yarn cypress run --browser ${{ matrix.browser.name }}

  js_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: yarn
      - run: yarn jest --passWithNoTests
